using System.Text;

namespace URMT.Export {
    public class PowerShellCodeGenerator {
        public readonly StringBuilder Code = new StringBuilder();
        public string Path { get; private set; }

        public PowerShellCodeGenerator(string path) {
            this.Path = path;

            AddLine("<#");
            AddLine(" Generated by Unity Rounds Modding Tools");
            AddLine(" DO NOT MODIFY THIS FILE MANUALLY, IT WILL BE OVERWRITTEN BY THE MODDING TOOLS");
            AddLine("#>\n");
        }

        public void AddLine(string line) {
            Code.AppendLine(line);
        }

        public void GenerateScript() {
            System.IO.File.WriteAllText(Path, Code.ToString());
        }
    }
}
